2022-11-16 10:48:51,266 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Configure stats pid to 1720607
2022-11-16 10:48:51,266 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Loading settings from /nfs/homedirs/zhz/.config/wandb/settings
2022-11-16 10:48:51,269 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Loading settings from /nfs/homedirs/zhz/uncertainty-quantification/src/posterior_networks/wandb/settings
2022-11-16 10:48:51,269 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-16 10:48:51,269 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-16 10:48:51,272 INFO    MainThread:1720607 [wandb_init.py:_log_setup():476] Logging user logs to /nfs/homedirs/zhz/uncertainty-quantification/src/posterior_networks/wandb/run-20221116_104851-p1l3v692/logs/debug.log
2022-11-16 10:48:51,272 INFO    MainThread:1720607 [wandb_init.py:_log_setup():477] Logging internal logs to /nfs/homedirs/zhz/uncertainty-quantification/src/posterior_networks/wandb/run-20221116_104851-p1l3v692/logs/debug-internal.log
2022-11-16 10:48:51,272 INFO    MainThread:1720607 [wandb_init.py:init():516] calling init triggers
2022-11-16 10:48:51,273 INFO    MainThread:1720607 [wandb_init.py:init():520] wandb.init called with sweep_config: {}
config: {}
2022-11-16 10:48:51,273 INFO    MainThread:1720607 [wandb_init.py:init():536] re-initializing run, found existing run on stack: 2085w5oe
2022-11-16 10:48:51,277 INFO    MainThread:1720607 [wandb_run.py:_finish():1746] finishing run uncertainty_tum/test-project/2085w5oe
2022-11-16 10:48:51,278 INFO    MainThread:1720607 [jupyter.py:save_history():448] not saving jupyter history
2022-11-16 10:48:51,280 INFO    MainThread:1720607 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-11-16 10:48:51,280 INFO    MainThread:1720607 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-11-16 10:48:51,280 INFO    MainThread:1720607 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-11-16 10:48:51,281 INFO    MainThread:1720607 [wandb_run.py:_restore():1932] restore
2022-11-16 10:48:51,281 INFO    MainThread:1720607 [wandb_run.py:_restore():1938] restore done
2022-11-16 10:48:57,545 INFO    MainThread:1720607 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2022-11-16 10:48:57,545 INFO    MainThread:1720607 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2022-11-16 10:48:57,558 INFO    MainThread:1720607 [wandb_run.py:_footer_sync_info():3333] logging synced files
2022-11-16 10:48:57,567 INFO    MainThread:1720607 [wandb_init.py:init():569] starting backend
2022-11-16 10:48:57,567 INFO    MainThread:1720607 [wandb_init.py:init():573] setting up manager
2022-11-16 10:48:57,574 INFO    MainThread:1720607 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-16 10:48:57,581 INFO    MainThread:1720607 [wandb_init.py:init():580] backend started and connected
2022-11-16 10:48:57,605 INFO    MainThread:1720607 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-11-16 10:48:57,605 INFO    MainThread:1720607 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-11-16 10:48:57,605 INFO    MainThread:1720607 [wandb_init.py:init():658] updated telemetry
2022-11-16 10:48:57,712 INFO    MainThread:1720607 [wandb_init.py:init():694] communicating run to backend with 60 second timeout
2022-11-16 10:48:59,181 INFO    MainThread:1720607 [wandb_run.py:_on_init():2000] communicating current version
2022-11-16 10:48:59,295 INFO    MainThread:1720607 [wandb_run.py:_on_init():2004] got version response 
2022-11-16 10:48:59,295 INFO    MainThread:1720607 [wandb_init.py:init():728] starting run threads in backend
2022-11-16 10:49:04,320 INFO    MainThread:1720607 [wandb_run.py:_console_start():1980] atexit reg
2022-11-16 10:49:04,320 INFO    MainThread:1720607 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2022-11-16 10:49:04,320 INFO    MainThread:1720607 [wandb_run.py:_redirect():1903] Wrapping output streams.
2022-11-16 10:49:04,320 INFO    MainThread:1720607 [wandb_run.py:_redirect():1925] Redirects installed.
2022-11-16 10:49:04,321 INFO    MainThread:1720607 [wandb_init.py:init():765] run started, returning control to user process
2022-11-16 10:54:01,211 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Configure stats pid to 1720607
2022-11-16 10:54:01,211 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Loading settings from /nfs/homedirs/zhz/.config/wandb/settings
2022-11-16 10:54:01,213 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Loading settings from /nfs/homedirs/zhz/uncertainty-quantification/src/posterior_networks/wandb/settings
2022-11-16 10:54:01,213 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-16 10:54:01,215 INFO    MainThread:1720607 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-16 10:54:01,215 INFO    MainThread:1720607 [wandb_init.py:_log_setup():476] Logging user logs to /nfs/homedirs/zhz/uncertainty-quantification/src/posterior_networks/wandb/run-20221116_105401-1aryukdu/logs/debug.log
2022-11-16 10:54:01,217 INFO    MainThread:1720607 [wandb_init.py:_log_setup():477] Logging internal logs to /nfs/homedirs/zhz/uncertainty-quantification/src/posterior_networks/wandb/run-20221116_105401-1aryukdu/logs/debug-internal.log
2022-11-16 10:54:01,217 INFO    MainThread:1720607 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7ff2bfd66f60>
2022-11-16 10:54:01,219 INFO    MainThread:1720607 [wandb_init.py:init():516] calling init triggers
2022-11-16 10:54:01,221 INFO    MainThread:1720607 [wandb_init.py:init():520] wandb.init called with sweep_config: {}
config: {}
2022-11-16 10:54:01,221 INFO    MainThread:1720607 [wandb_init.py:init():536] re-initializing run, found existing run on stack: p1l3v692
2022-11-16 10:54:01,225 INFO    MainThread:1720607 [wandb_run.py:_finish():1746] finishing run uncertainty_tum/test-project/p1l3v692
2022-11-16 10:54:01,225 INFO    MainThread:1720607 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-11-16 10:54:01,227 INFO    MainThread:1720607 [wandb_run.py:_restore():1932] restore
2022-11-16 10:54:01,227 INFO    MainThread:1720607 [wandb_run.py:_restore():1938] restore done
2022-11-16 10:54:06,486 INFO    MainThread:1720607 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2022-11-16 10:54:06,487 INFO    MainThread:1720607 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2022-11-16 10:54:06,497 INFO    MainThread:1720607 [wandb_run.py:_footer_sync_info():3333] logging synced files
